reorder_imports = true

# unstable features, use nightly: `rustup run nightly cargo fmt`
imports_granularity = "Module"
format_code_in_doc_comments = true
format_macro_bodies = true
format_strings = true

ignore = [
    "**/proto/**/*.rs",
]