name: 'Setup Environment'
description: 'Install Protoc and Rust toolchain'
inputs:
  github_token:
    description: 'GitHub Token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b  #v3.0.0
      with:
        version: "25.3"
        repo-token: ${{ inputs.github_token }}

    - name: Setup Rust nightly toolchain
      uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
      with:
        toolchain: nightly
        components: rustfmt

    - name: Setup Rust stable toolchain
      uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
      with:
        toolchain: stable
        components: clippy
