name: Coverage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    name: Run tests and generate coverage report
    runs-on: ubuntu-latest

    env:
      SPIFFE_ENDPOINT_SOCKET: "unix:/tmp/spire-agent/public/api.sock"
      SPIFFE_ENDPOINT_SOCKET_FEDERATED: "unix:/tmp/spire-agent-federated/public/api.sock"
      SPIRE_ADMIN_ENDPOINT_SOCKET: "unix:/tmp/spire-agent/admin/api.sock"

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Install toolchain
        uses: ./.github/actions/setup-env
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache project
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Install LLVM tools
        run: rustup component add llvm-tools-preview

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --locked

      - name: Start SPIRE
        run: .github/workflows/scripts/run-spire.sh

      - name: Generate LCOV coverage report
        run: |
          make coverage
          .github/workflows/scripts/filter-lcov.sh lcov.info

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./lcov.info

      - name: Clean up SPIRE
        if: always()
        run: .github/workflows/scripts/cleanup-spire.sh
